modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT License"
issueTrackerURL = "https://github.com/Mrthomas20121/Blue-Skies-Tcon/issues"

[[mods]]
modId = "blue_skies_tcon"
version = "0.0.2"
displayName = "Blue Skies Tinkers Compat"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/blue_skies_tcon"
authors = "Mrthomas20121"
description = '''
Add Tinkers Compat to Blue Skies
'''

[[dependencies.blue_skies_tcon]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.blue_skies_tcon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.blue_skies_tcon]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.5.1.31,)"
    ordering="NONE"
    side="BOTH"