modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT License"
issueTrackerURL = "https://github.com/Mrthomas20121-Mods/Blue-Skies-Tconissues"

[[mods]]
modId = "blue_skies_tcon"
version = "${mod_version}"
displayName = "Blue Skies Tinkers Compat"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/blue_skies_tcon"
authors = "Mrthomas20121, paypur"
description = '''
Add Blue Skies Compat to Tinkers Construct
'''

[[dependencies.blue_skies_tcon]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.blue_skies_tcon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"
[[dependencies.blue_skies_tcon]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.9.2,)"
    ordering="NONE"
    side="BOTH"